### ISSUE TITLE
output_value_hook

### ISSUE THREAD

**Issue by kilik128** [MB-29/optimal-textures#3]
Traceback (most recent call last):
  File "run.py", line 10, in <module>
    from style_transfer import StyleTransfer
  File "/content/optimal-textures/style_transfer.py", line 5, in <module>
    from utils import output_value_hook, sliced_transport, image_preprocessing, vgg_normalization
ImportError: cannot import name 'output_value_hook' from 'utils' (/content/optimal-textures/utils.py)

**Comment by MB-29** [comment]
Thanks, it should be solved now.
